In [1]:
import pandas as pd
import numpy as np

In [49]:
df=pd.read_csv(r"C:\Users\Sam\OneDrive\Desktop\marketing_campaign_dataset.csv")
df.head(10)

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,"$16,174.00",6.29,Chicago,Spanish,506,1922,6,Health & Wellness,2021-01-01
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,"$11,566.00",5.61,New York,German,116,7523,7,Fashionistas,2021-01-02
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,"$10,200.00",7.18,Los Angeles,French,584,7698,1,Outdoor Adventurers,2021-01-03
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,"$12,724.00",5.55,Miami,Mandarin,217,1820,7,Health & Wellness,2021-01-04
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,"$16,452.00",6.50,Los Angeles,Mandarin,379,4201,3,Health & Wellness,2021-01-05
5,6,DataTech Solutions,Display,All Ages,15 days,Instagram,0.07,"$9,716.00",4.36,New York,German,100,1643,1,Foodies,2021-01-06
6,7,NexGen Systems,Email,Women 35-44,60 days,Website,0.13,"$11,067.00",2.86,Los Angeles,Spanish,817,8749,10,Tech Enthusiasts,2021-01-07
7,8,DataTech Solutions,Search,Men 18-24,45 days,Google Ads,0.08,"$13,280.00",5.55,Los Angeles,Mandarin,624,7854,7,Outdoor Adventurers,2021-01-08
8,9,Alpha Innovations,Social Media,Women 35-44,15 days,Facebook,0.09,"$18,066.00",6.73,Chicago,German,861,1754,6,Tech Enthusiasts,2021-01-09
9,10,TechCorp,Email,Women 35-44,15 days,Instagram,0.09,"$13,766.00",3.78,Los Angeles,English,642,3856,3,Tech Enthusiasts,2021-01-10

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       200000 non-null  int64
 1   Company           200000 non-null  object
 2   Campaign_Type     200000 non-null  object
 3   Target_Audience   200000 non-null  object
 4   Duration          200000 non-null  object
 5   Channel_Used      200000 non-null  object
 6   Conversion_Rate   200000 non-null  float64
 7   Acquisition_Cost  200000 non-null  object
 8   ROI               200000 non-null  float64
 9   Location          200000 non-null  object
 10  Language          200000 non-null  object
 11  Clicks            200000 non-null  int64
 12  Impressions       200000 non-null  int64
 13  Engagement_Score  200000 non-null  int64
 14  Customer_Segment  200000 non-null  object
 15  Date              200000 non-null  object
dtypes: float64(2), int64(4), object(10)
memory usage: 24.4+ MB

In [51]:
df[df.duplicated(subset=['Campaign_ID', 'Date', 'Channel_Used'])]

Empty DataFrame
Columns: [Campaign_ID, Company, Campaign_Type, Target_Audience, Duration, Channel_Used, Conversion_Rate, Acquisition_Cost, ROI, Location, Language, Clicks, Impressions, Engagement_Score, Customer_Segment, Date]
Index: []

Checking Null values

In [52]:
df.isnull().sum()

Campaign_ID         0
Company             0
Campaign_Type       0
Target_Audience     0
Duration            0
Channel_Used        0
Conversion_Rate     0
Acquisition_Cost    0
ROI                 0
Location            0
Language            0
Clicks              0
Impressions         0
Engagement_Score    0
Customer_Segment    0
Date                0
dtype: int64

checking Duplicates

In [53]:
for col in df.columns:
    x=df[col].duplicated().sum()
    print(col,'=',x)

Campaign_ID = 0
Company = 199995
Campaign_Type = 199995
Target_Audience = 199995
Duration = 199996
Channel_Used = 199994
Conversion_Rate = 199985
Acquisition_Cost = 184999
ROI = 199399
Location = 199995
Language = 199995
Clicks = 199099
Impressions = 190999
Engagement_Score = 199990
Customer_Segment = 199995
Date = 199635

chaning datatype

In [54]:
df['Date']=pd.to_datetime(df['Date'],errors='coerce')

checking not_available(N/a) & Not a Number(Nan)

In [55]:
df.isna().sum()

Campaign_ID         0
Company             0
Campaign_Type       0
Target_Audience     0
Duration            0
Channel_Used        0
Conversion_Rate     0
Acquisition_Cost    0
ROI                 0
Location            0
Language            0
Clicks              0
Impressions         0
Engagement_Score    0
Customer_Segment    0
Date                0
dtype: int64

Checking metrice are valid (non-negative).

In [56]:
List=['Impressions','Clicks','Conversion_Rate','ROI']
for x in List:
    x=(df[x]>=0).all()
    print(x)

True
True
True
True

removing noice from columns

In [59]:
df['Acquisition_Cost']=df['Acquisition_Cost'].str.strip('$')

In [66]:
df['Acquisition_Cost']=df['Acquisition_Cost'].str.replace(',','')

In [73]:
df['Acquisition_Cost']=df['Acquisition_Cost'].astype('float64')

Saving the csv-file

In [79]:
df.to_csv('Marketing_Campaign_Performance_Dataset2.csv',index=False)

In [80]:
df.columns

Index(['Campaign_ID', 'Company', 'Campaign_Type', 'Target_Audience',
       'Duration', 'Channel_Used', 'Conversion_Rate', 'Acquisition_Cost',
       'ROI', 'Location', 'Language', 'Clicks', 'Impressions',
       'Engagement_Score', 'Customer_Segment', 'Date'],
      dtype='object')

Calculating Key metrics

In [91]:
df['cost']=df['Clicks']*df['Acquisition_Cost']
df['CTR_(Click-Through Rate)']=df['Clicks']/df['Impressions']
df['CPC (Cost per Click)']=df['cost']/df['Clicks']
df['Conversions']=df['Conversion_Rate']*df['Clicks']
df['CPA (Cost per Acquisition)']=df['cost']/df['Conversions']
#→ Revenue = Cost × (1 + (ROI / 100))
df['Revenue']=df['cost']*(1+(df['ROI']/100))
#ROI (%) = ((Revenue - Cost) / Cost) × 100
df['ROI (%)']=(df['Revenue']-df['cost'])*100

In [92]:
df

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,...,Engagement_Score,Customer_Segment,Date,cost,CTR_(Click-Through Rate),CPC (Cost per Click),Conversions,CPA (Cost per Acquisition),Revenue,ROI (%)
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,16174.0,6.29,Chicago,...,6,Health & Wellness,2021-01-01,8184044.0,0.263267,16174.0,20.24,4.043500e+05,8.698820e+06,51477636.76
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,11566.0,5.61,New York,...,7,Fashionistas,2021-01-02,1341656.0,0.015419,11566.0,13.92,9.638333e+04,1.416923e+06,7526690.16
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,10200.0,7.18,Los Angeles,...,1,Outdoor Adventurers,2021-01-03,5956800.0,0.075864,10200.0,40.88,1.457143e+05,6.384498e+06,42769824.00
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,12724.0,5.55,Miami,...,7,Health & Wellness,2021-01-04,2761108.0,0.119231,12724.0,23.87,1.156727e+05,2.914349e+06,15324149.40
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,16452.0,6.50,Los Angeles,...,3,Health & Wellness,2021-01-05,6235308.0,0.090217,16452.0,18.95,3.290400e+05,6.640603e+06,40529502.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,199996,TechCorp,Display,All Ages,30 days,Google Ads,0.06,18365.0,2.84,Chicago,...,1,Tech Enthusiasts,2021-12-07,15757170.0,0.143287,18365.0,51.48,3.060833e+05,1.620467e+07,44750362.80
199996,199997,DataTech Solutions,Email,Men 25-34,15 days,Facebook,0.02,8168.0,4.14,Chicago,...,7,Foodies,2021-12-08,1862304.0,0.074316,8168.0,4.56,4.084000e+05,1.939403e+06,7709938.56
199997,199998,DataTech Solutions,Social Media,Men 18-24,45 days,Website,0.05,13397.0,3.25,New York,...,3,Tech Enthusiasts,2021-12-09,9686031.0,0.075723,13397.0,36.15,2.679400e+05,1.000083e+07,31479600.75
199998,199999,Innovate Industries,Influencer,All Ages,30 days,YouTube,0.10,18508.0,3.86,Houston,...,1,Foodies,2021-12-10,9772224.0,0.191097,18508.0,52.80,1.850800e+05,1.014943e+07,37720784.64
199999,200000,Innovate Industries,Social Media,Women 35-44,45 days,Google Ads,0.01,13835.0,6.64,Chicago,...,8,Tech Enthusiasts,2021-12-11,12783540.0,0.126801,13835.0,9.24,1.383500e+06,1.363237e+07,84882705.60